-- Limpar dados de exemplo
DELETE FROM games;

-- Importar jogos da lista do usuário
-- Plataforma padrão: Nintendo Wii (maioria dos jogos da lista)
INSERT INTO games (name, platform, status) VALUES
('Absolum', 'Nintendo Wii', 'Zerado'),
('Alex Kidd In Miracle World DX', 'Nintendo Wii', 'Zerado'),
('Alice In Wonderland', 'Nintendo Wii', 'Zerado'),
('Arc Rise Fantasia', 'Nintendo Wii', 'Zerado'),
('Band Hero', 'Nintendo Wii', 'Casual'),
('Banjo-Kazooie', 'Nintendo Wii', 'Zerado'),
('Banjo-Tooie', 'Nintendo Wii', 'A Jogar'),
('Bayonetta 1', 'Nintendo Wii', 'Zerado'),
('Bayonetta 2', 'Nintendo Wii', 'Zerado'),
('Bayonetta 3', 'Nintendo Wii', 'Zerado'),
('Big Brain Academy', 'Nintendo Wii', 'Casual'),
('Bloodstained Ritual of the Night', 'Nintendo Wii', 'Zerado'),
('Boy and His Blob', 'Nintendo Wii', 'Zerado'),
('Call of Duty: Black Ops', 'Nintendo Wii', 'Zerado'),
('Call of Duty: Modern Warfare 3', 'Nintendo Wii', 'Zerado'),
('Castle of Ilusion', 'Nintendo Wii', 'Zerado'),
('Contra Operation Galuga', 'Nintendo Wii', 'Zerado'),
('Country Dance', 'Nintendo Wii', 'Casual'),
('Crash Bandicoot', 'Nintendo Wii', 'Zerado'),
('Cronos - The New Dawn', 'Nintendo Wii', 'A Jogar'),
('Cursed Mountain', 'Nintendo Wii', 'Zerado'),
('Dead Rising', 'Nintendo Wii', 'Zerado'),
('Dead Space', 'Nintendo Wii', 'Zerado'),
('Deca Sports 3', 'Nintendo Wii', 'Casual'),
('Disaster', 'Nintendo Wii', 'Zerado'),
('Disney Epic Mickey 1', 'Nintendo Wii', 'Zerado'),
('Disney Epic Mickey 2', 'Nintendo Wii', 'Zerado'),
('DJ Hero 1', 'Nintendo Wii', 'Casual'),
('DJ Hero 2', 'Nintendo Wii', 'Casual'),
('Donkey Kong Country Returns', 'Nintendo Wii', 'Zerado'),
('Doom Eternal', 'PC', 'A Jogar'),
('Double Dragon Revive', 'Nintendo Wii', 'A Jogar'),
('Dracula Collection', 'Nintendo Wii', 'A Jogar'),
('Dragon Ball Z Budokai Tenkaichi 3', 'Nintendo Wii', 'Casual'),
('Dragon Ball: Revenge of King Piccolo', 'Nintendo Wii', 'Zerado'),
('Dragon Quest 1 HD', 'Nintendo Switch', 'A Jogar'),
('Dragon Quest 2 HD', 'Nintendo Switch', 'A Jogar'),
('Dragon Quest 3 HD', 'Nintendo Switch', 'Zerado'),
('Dragon Quest 7 Reimagined', 'Nintendo Wii', 'A Jogar'),
('Dragon Quest Swords', 'Nintendo Wii', 'Zerado'),
('DuckTales: Remastered', 'Nintendo Wii', 'Zerado'),
('Dying Light: The Beast', 'PC', 'A Jogar'),
('Eiyuden', 'Nintendo Wii', 'Zerado'),
('Expedition 33', 'PC', 'A Jogar'),
('Fantasian Neo Dimension', 'Nintendo Switch', 'Zerado'),
('Fatal Frame 4', 'Nintendo Wii', 'Zerado'),
('Final Fantasy The Crystal Bearers', 'Nintendo Wii', 'Zerado'),
('Get Up and Dance', 'Nintendo Wii', 'Casual'),
('Ghosts n Goblins Resurrection', 'Nintendo Switch', 'A Jogar'),
('Go Vacation', 'Nintendo Wii', 'Casual'),
('Grandia Collection', 'Nintendo Switch', 'A Jogar'),
('Guitar Hero 3', 'Nintendo Wii', 'Casual'),
('Guitar Hero 5', 'Nintendo Wii', 'Casual'),
('Guitar Hero Aerosmith', 'Nintendo Wii', 'Casual'),
('Guitar Hero Metallica', 'Nintendo Wii', 'Casual'),
('Guitar Hero Smash Hits', 'Nintendo Wii', 'Casual'),
('Guitar Hero Van Halen', 'Nintendo Wii', 'Casual'),
('Guitar Hero Warriors of Rock', 'Nintendo Wii', 'Casual'),
('Guitar Hero World Tour', 'Nintendo Wii', 'Casual'),
('Hell is Us', 'PC', 'A Jogar'),
('Horizon Chase', 'Nintendo Wii', 'Zerado'),
('Just Dance 1', 'Nintendo Wii', 'Casual'),
('Just Dance 2', 'Nintendo Wii', 'Casual'),
('Just Dance 2014', 'Nintendo Wii', 'Casual'),
('Just Dance 2015', 'Nintendo Wii', 'Casual'),
('Just Dance 2016', 'Nintendo Wii', 'Casual'),
('Just Dance 2017', 'Nintendo Wii', 'Casual'),
('Just Dance 2018', 'Nintendo Wii', 'Casual'),
('Just Dance 2019', 'Nintendo Wii', 'Casual'),
('Just Dance 3', 'Nintendo Wii', 'Casual'),
('Just Dance 4', 'Nintendo Wii', 'Casual'),
('Just Dance Black Eyed Peas', 'Nintendo Wii', 'Casual'),
('Just Dance Hip Hop Dance Experience', 'Nintendo Wii', 'Casual'),
('Just Dance Michael Jackson', 'Nintendo Wii', 'Casual'),
('Just Dance Summer Party', 'Nintendo Wii', 'Casual'),
('Kingdom Hearts HD 1.5 Re:Chain of Memories + filme 358/2 Days', 'PlayStation 4', 'A Jogar'),
('Kingdom Hearts HD 1.5 Remix Kingdom Hearts Final Mix', 'PlayStation 4', 'A Jogar'),
('Kingdom Hearts HD 2.5 Remix Birth by Sleep Final Mix', 'PlayStation 4', 'A Jogar'),
('Kingdom Hearts HD 2.8 0.2 Birth by Sleep', 'PlayStation 4', 'A Jogar'),
('Kingdom Hearts HD 2.8 Dream Drop Distance HD', 'PlayStation 4', 'A Jogar'),
('Kingdom Hearts II Final Mix + filme Re:coded', 'PlayStation 4', 'A Jogar'),
('Kingdom Hearts III Re Mind DLC', 'PlayStation 4', 'A Jogar'),
('Kingdom Hearts: Melody of Memory', 'PlayStation 4', 'A Jogar'),
('Kirby', 'Nintendo Wii', 'Zerado'),
('Kirbys Epic Yarn', 'Nintendo Wii', 'Zerado'),
('Lost in Shadow', 'Nintendo Wii', 'Zerado'),
('Luigis Mansion 1', 'Nintendo Wii', 'Zerado'),
('Luigis Mansion 2', 'Nintendo 3DS', 'Zerado'),
('Luigis Mansion 3', 'Nintendo Switch', 'Zerado'),
('Mandragora', 'PC', 'A Jogar'),
('Manhunt 2', 'Nintendo Wii', 'Zerado'),
('Mario & Luigi Brothership', 'Nintendo Switch', 'A Jogar'),
('Mario & Sonic at The Olympic Games 1', 'Nintendo Wii', 'Casual'),
('Mario & Sonic at The Olympic Games 2', 'Nintendo Wii', 'Casual'),
('Mario & Sonic at The Winter Games', 'Nintendo Wii', 'Casual'),
('Mario Kart', 'Nintendo Wii', 'Casual'),
('Mario Kart 8', 'Nintendo Switch', 'Casual'),
('Mario Party 9', 'Nintendo Wii', 'Casual'),
('Mario Sports Mix', 'Nintendo Wii', 'Casual'),
('Mario Strikers Charged', 'Nintendo Wii', 'Casual'),
('Mario Super Sluggers', 'Nintendo Wii', 'Casual'),
('Mario Tennis', 'Nintendo Wii', 'Casual'),
('Mega Man 11', 'Nintendo Switch', 'A Jogar'),
('Metal Slug: Awakening', 'PC', 'A Jogar'),
('Metroid Prime 1', 'Nintendo Wii', 'A Jogar'),
('Metroid Prime 2', 'Nintendo Wii', 'A Jogar'),
('Metroid Prime 3', 'Nintendo Wii', 'A Jogar'),
('Mini Golf Resort', 'Nintendo Wii', 'Casual'),
('MIO: Memories In Orbit', 'PC', 'A Jogar'),
('Monster Boy and the Cursed Kingdom', 'Nintendo Switch', 'A Jogar'),
('Monster Hunter Tri', 'Nintendo Wii', 'Casual'),
('Mr Bones', 'PC', 'A Jogar'),
('Muramasa', 'Nintendo Wii', 'Zerado'),
('NBA Jam', 'Nintendo Wii', 'Casual'),
('New Joe and Mac', 'Nintendo Switch', 'A Jogar'),
('New Super Mario Bros', 'Nintendo Wii', 'Zerado'),
('Nikoderiko', 'Nintendo Switch', 'A Jogar'),
('Ninja Gaiden - Ragebound', 'PC', 'A Jogar'),
('Okami', 'Nintendo Wii', 'Zerado'),
('Oops Prank Party', 'Nintendo Wii', 'Casual'),
('Pandoras Tower', 'Nintendo Wii', 'Zerado'),
('Paper Mario The Thousand-Year Door', 'Nintendo Switch', 'A Jogar'),
('Perfect Dark', 'Xbox', 'A Jogar'),
('Prince of Persia Rival Swords', 'Nintendo Wii', 'Zerado'),
('Prince of Persia the Forgotten Sands', 'Nintendo Wii', 'Zerado'),
('Princess Peach Showtime', 'Nintendo Switch', 'A Jogar'),
('Punch Out', 'Nintendo Wii', 'Zerado'),
('Resident Evil 0', 'Nintendo Wii', 'A Jogar'),
('Resident Evil 1', 'Nintendo Wii', 'A Jogar'),
('Resident Evil 2', 'Nintendo Wii', 'A Jogar'),
('Resident Evil 3', 'Nintendo Wii', 'A Jogar'),
('Resident Evil 4', 'Nintendo Wii', 'A Jogar'),
('Resident Evil 5', 'Nintendo Wii', 'A Jogar'),
('Resident Evil 6', 'Nintendo Wii', 'A Jogar'),
('Resident Evil 7', 'PC', 'A Jogar'),
('Resident Evil 8', 'PC', 'A Jogar'),
('Resident Evil 9', 'PC', 'A Jogar'),
('Resident Evil Code Veronica', 'Nintendo Wii', 'A Jogar'),
('Resident Evil Revelation 1', 'Nintendo Wii', 'A Jogar'),
('Resident Evil Revelation 2', 'Nintendo Wii', 'A Jogar'),
('Rock Band 2', 'Nintendo Wii', 'Casual'),
('Rock Band 3', 'Nintendo Wii', 'Casual'),
('Rock Band Beatles', 'Nintendo Wii', 'Casual'),
('Rock Band Green Day', 'Nintendo Wii', 'Casual'),
('Rygar The Battle Of Argus', 'Nintendo Wii', 'A Jogar'),
('Samurai Warriors 3', 'Nintendo Wii', 'A Jogar'),
('Sengoku Basara Samurai Heroes', 'Nintendo Wii', 'A Jogar'),
('Shadow of the Ninja Reborn', 'Nintendo Switch', 'A Jogar'),
('Shenmue 1', 'PC', 'A Jogar'),
('Shenmue 2', 'PC', 'A Jogar'),
('Shenmue 3', 'PC', 'A Jogar'),
('Shinobi - Art of Vengeance', 'PC', 'A Jogar'),
('Shiren the Wanderer', 'Nintendo Wii', 'A Jogar'),
('Silent Hill Shattered Memories', 'Nintendo Wii', 'A Jogar'),
('Sonic & Sega All-Stars Racing', 'Nintendo Wii', 'Casual'),
('Sonic and the Black Knight', 'Nintendo Wii', 'A Jogar'),
('Sonic Colors', 'Nintendo Wii', 'A Jogar'),
('Sonic Riders Zero Gravity', 'Nintendo Wii', 'A Jogar'),
('Sonic Unleashed', 'Nintendo Wii', 'A Jogar'),
('Spectrobes Origins', 'Nintendo Wii', 'A Jogar'),
('Speed Racer', 'Nintendo Wii', 'Casual'),
('Star Wars the Force Unleashed 1', 'Nintendo Wii', 'A Jogar'),
('Star Wars the Force Unleashed 2', 'Nintendo Wii', 'A Jogar'),
('Streets of Rage 4', 'Nintendo Switch', 'Zerado'),
('Strider', 'Nintendo Wii', 'Jogando'),
('Summer Athletics 2009', 'Nintendo Wii', 'Casual'),
('Super Mario Galaxy 1', 'Nintendo Wii', 'Zerado'),
('Super Mario Galaxy 2', 'Nintendo Wii', 'A Jogar'),
('Super Mario Odyssey', 'Nintendo Switch', 'A Jogar'),
('Super Mario Party Jamboree', 'Nintendo Switch', 'Casual'),
('Super Mario Wonder', 'Nintendo Switch', 'Zerado'),
('Super Paper Mario', 'Nintendo Wii', 'A Jogar'),
('Super Smash Bros Brawl', 'Nintendo Wii', 'Casual'),
('Tales of Graces', 'Nintendo Wii', 'A Jogar'),
('Tales of Symphonia Dawn of the New World', 'Nintendo Wii', 'A Jogar'),
('Tales of Xillia Remastered', 'PlayStation 4', 'A Jogar'),
('Teenage Mutant Ninja Turtles: Shredders Revenge', 'Nintendo Switch', 'A Jogar'),
('Tenchu Shadows Assassins', 'Nintendo Wii', 'A Jogar'),
('The Calling', 'Nintendo Wii', 'A Jogar'),
('The Conduit 1', 'Nintendo Wii', 'A Jogar'),
('The Conduit 2', 'Nintendo Wii', 'A Jogar'),
('The House of the Dead Collection', 'Nintendo Wii', 'A Jogar'),
('The House of the Dead Overkill', 'Nintendo Wii', 'A Jogar'),
('The Last Story', 'Nintendo Wii', 'A Jogar'),
('The Legend of Oasis', 'Nintendo Wii', 'A Jogar'),
('The Legend of Zelda Skyward Sword', 'Nintendo Wii', 'A Jogar'),
('The Legend of Zelda Twilight Princess', 'Nintendo Wii', 'A Jogar'),
('The Legend of Zelda: Breath of the Wild', 'Nintendo Switch', 'A Jogar'),
('The Legend of Zelda: Echoes of Wisdom', 'Nintendo Switch', 'A Jogar'),
('The Legend of Zelda: Tears of the Kingdom', 'Nintendo Switch', 'A Jogar'),
('The Witcher', 'PC', 'A Jogar'),
('Tiger Woods PGA Tour 2012', 'Nintendo Wii', 'Casual'),
('Top Spin 4', 'Nintendo Wii', 'Casual'),
('Towa and the Guardians of the Sacred Tree', 'Nintendo Switch', 'A Jogar'),
('Trails Beyond the Horizon', 'PC', 'A Jogar'),
('Trails from Zero', 'PC', 'A Jogar'),
('Trails in the Sky FC', 'PC', 'A Jogar'),
('Trails in the Sky SC', 'PC', 'A Jogar'),
('Trails in the Sky TR', 'PC', 'A Jogar'),
('Trails into Reverie', 'PC', 'A Jogar'),
('Trails of Cold Steel', 'PC', 'A Jogar'),
('Trails of Cold Steel II', 'PC', 'A Jogar'),
('Trails of Cold Steel III', 'PC', 'A Jogar'),
('Trails of Cold Steel IV', 'PC', 'A Jogar'),
('Trails through Daybreak', 'PC', 'A Jogar'),
('Trails through Daybreak II', 'PC', 'A Jogar'),
('Trails to Azure', 'PC', 'A Jogar'),
('Trauma Center New Blood', 'Nintendo Wii', 'A Jogar'),
('Trauma Center Second Opinion', 'Nintendo Wii', 'A Jogar'),
('Trauma Team', 'Nintendo Wii', 'A Jogar'),
('Turok 2: Seeds of Evil', 'Nintendo Wii', 'A Jogar'),
('Turok 3: Shadow of Oblivion', 'Nintendo Wii', 'A Jogar'),
('Turok: Dinosaur Hunter', 'Nintendo Wii', 'A Jogar'),
('Turok: Evolution', 'Nintendo Wii', 'A Jogar'),
('Valhalla Knights Eldar Saga', 'Nintendo Wii', 'A Jogar'),
('Virtua Tennis 4', 'Nintendo Wii', 'Casual'),
('Wario Land Shake It!', 'Nintendo Wii', 'A Jogar'),
('Wii Party', 'Nintendo Wii', 'Casual'),
('Wii Play', 'Nintendo Wii', 'Casual'),
('Wii Sports', 'Nintendo Wii', 'Casual'),
('Wii Sports Resort', 'Nintendo Wii', 'Casual'),
('Winter Sports 2012', 'Nintendo Wii', 'Casual'),
('Xenoblade Chronicles 2', 'Nintendo Switch', 'A Jogar'),
('Xenoblade Chronicles 3', 'Nintendo Switch', 'A Jogar'),
('Xenoblade Chronicles X', 'Nintendo Wii', 'A Jogar'),
('Xenoblade Chronicles: Definitive Edition', 'Nintendo Switch', 'A Jogar'),
('Xuan Yuan Sword', 'PC', 'A Jogar'),
('Zack and Wiki Quest for Barbaros Treasure', 'Nintendo Wii', 'A Jogar');
